# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Y2UyNWIzN2IyZmU3OTViOTk0MDhkOThjZjM1OTIyMThiN2U5OTNjYjI5NzhiMzQwMDA1NDI3MDc3ZjFhOGE3N2RmNWE4YWZhNTVmNjEyZmViNGY5YTJmZDY5NDVhZGM3NmMzNjI3ODk5ZWNkY2RhODIxYTZhMjkxZTljZjkxNzg=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
